# Generated by Django 5.1.15 on 2026-05-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initials', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=40)),
                ('interview_date', models.CharField(blank=True, max_length=60, null=True)),
                ('interview_time', models.CharField(blank=True, max_length=30, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=40, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('interview_type', models.CharField(default='Technical', max_length=100)),
                ('interviewer', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.CharField(default='45 min', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('interview_questions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interview_links',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('verdict', models.CharField(default='HOLD', max_length=20)),
                ('total_score', models.IntegerField(default=0)),
                ('tech_score', models.IntegerField(default=0)),
                ('comm_score', models.IntegerField(default=0)),
                ('integrity_score', models.IntegerField(default=0)),
                ('recording_data', models.TextField(blank=True, null=True)),
                ('video_buffer', models.BinaryField(blank=True, null=True)),
                ('video_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('responses', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_recordings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(default='Full-time', max_length=100)),
                ('salary', models.CharField(blank=True, default='', max_length=255)),
                ('applicants', models.IntegerField(default=0)),
                ('color', models.CharField(default='blue', max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('openings', models.IntegerField(default=1)),
                ('is_remote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_posts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_sets',
            },
        ),
        migrations.CreateModel(
            name='ResumeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initials', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('technical', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('domain', models.IntegerField(default=0)),
                ('gap', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('missing', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='Upload', max_length=100)),
                ('formatted', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('jd_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resume_scores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserEmailConfig',
            fields=[
                ('user_email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.CharField(blank=True, default='', max_length=10)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_secure', models.BooleanField(default=False)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('social', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_email_config',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('alt_email', models.CharField(blank=True, default='', max_length=255)),
                ('blood_group', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=60)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_mime', models.CharField(blank=True, default='', max_length=100)),
                ('file_data', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_documents',
                'unique_together': {('user_email', 'doc_type')},
            },
        ),
    ]
